# Declare variables to be passed into your templates.

replicaCount: 2

# Choose deployment type: "build" or "image"
deploymentType: "build"

# BuildConfig settings (used when deploymentType: "build")
buildConfig:
  triggerBuild:
    enabled: false             # Enable or disable the build trigger Job for argocd
  gitUri: "https://github.com/brian316/Demo-Mesh-Predictor.git"                  # URL of the git repository
  gitRef: "main"              # Branch of the git repository
  contextDir: ""
  strategy: Docker
  dockerfilePath: Dockerfile  # Path to the Dockerfile
  sourceSecret:               # Secret containing the SSH keys
    type: ""               # "ssh" or "pat (github personal access token)"
    name: ""                  # Name of the secret

# Image settings (used when deploymentType: "image")
image:
  name: ""                    # Image name to pull
  tag: "latest"               # Image tag to pull
  pullSecret: ""              # Optional: name of the pull secret for private repositories

# application settings (common for both deployment types)
application:
  # For buildConfig: image is automatically set from the buildConfig output
  # For image: will use image.name:image.tag
  pullPolicy: Always
  env:
    - LOGGING_CONFIG_PATH: "/tmp/app.log" # If you want to set a logging path
    - gt4sd_local_cache_path: "/data/.openad_models" # !important mount checkpoints to this Volume
    - ENABLE_CACHE_RESULTS: "True" # enable cache for inference results, enable only for deterministic 
    - ASYNC_ALLOW: "True"  # enable async inference
    - WORKER_COUNT: 1
    - AUTO_GARBAGE_COLLECT: True
    - AUTO_CLEAR_GPU_MEM: True
    - UPLOAD_STORAGE_DIR: "/data/collection_uploads"  # Directory for temporary file uploads
    - ASYNC_JOB_PATH: "/data/async_jobs/openad_async_jobs"  # Directory for async job status / results
    - COLLECTIONS_API_ENABLED: True
    - REDIS_HOST: "redis-master.redis.svc.cluster.local"  # Hostname for Redis connection
    - REDIS_PASSWORD: "REMOVED_SECRET"  # Password for Redis connection
  # List of Secrets or ConfigMaps to inject into the init container and main containers as environment variables
  envFrom: []
  #   - secretRef:
  #       name: aws-credentials
  #   - configMapRef:
  #       name: config-map-name

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  # type: NodePort
  port: 80
  targetPort: 8080 # Internal port of your application

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    # nvidia.com/gpu: 1
    cpu: 2000m # 2 CPU cores
    memory: "4Gi"
  requests:
    # nvidia.com/gpu: 1
    cpu: 1000m # 1 CPU cores (adjust if necessary)
    memory: "2Gi"

livenessProbe:
  httpGet:
    path: /health
    port: 8081
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

storage:
  create: false # Set to true if you want to create a PersistentVolumeClaim
  name: "test-data-pvc" # unique name for the storage
  className: ""
  accessMode: ReadWriteMany
  size: 100Gi

volumes:
  - name: test-data-pvc
    persistentVolumeClaim:  # Uncomment to use a PVC
      claimName: test-data-pvc  # name of the PVC to use

volumeMounts:
  - name: test-data-pvc
    mountPath: "/data"

# sidecar container config to continuously sync s3 resources
s3sync:
  enabled: false
  image: "amazon/aws-cli"
  region: "us-east-1"         # AWS region
  syncInterval: "60"          # in seconds
  targets:
    - s3Uri: ""               # e.g., "s3://my-bucket/path/"
      localPath: ""           # "/data/.openad_models/..."
      direction: "s3tolocal"  # direction options: "s3tolocal" (default), "localtos3", "twoway"

nodeSelector: {}

tolerations: []
#   - key: "nvidia.com/gpu"
#     effect: "NoSchedule"

affinity: {}
