# {{- if eq .Values.deploymentType "build" }}
# always create imagestream even if buildConfig is not used
# ensures that images are not deleted if switching to image deployment later
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "openad-model.fullname" . }}
  labels:
    {{- include "openad-model.labels" . | nindent 4 }}
spec:
  tags:
    - name: "latest"
      from:
        kind: ImageStreamTag
        name: "{{ include "openad-model.fullname" . }}:latest"
# {{- end }}
