{{- if .Values.storage.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.name }}
  annotations:
    "helm.sh/resource-policy": keep
    "argocd.argoproj.io/sync-options": "Prune=false"
  labels:
    {{- include "openad-model.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
